spring.application.name=employee-api

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=employee_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa123***

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080

//spring.mvc.hiddenmethod.filter.enabled=true